--- #YAML:1.0
name:               Rose-DBx-Object-Indexed
version:            0.006
abstract:           full-text search for RDBO classes
author:
    - Peter Karman <karman@cpan.org>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Class::C3:            0
    Rose::DB::Object:     0
    Rose::DBx::Object::MoreHelpers:  0
    Rose::DBx::TestDB:    0.05
    Scalar::Util:         0
    SWISH::Prog:          0.25
    Test::More:           0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.54
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
