---
abstract: 'full-text search for RDBO classes'
author:
  - 'Peter Karman <karman@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.112150'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Rose-DBx-Object-Indexed
no_index:
  directory:
    - t
    - inc
requires:
  Class::C3: 0
  Rose::DB::Object: 0
  Rose::DBx::Object::MoreHelpers: 0
  Rose::DBx::TestDB: 0.05
  SWISH::Prog: 0.48
  Scalar::Util: 0
  Test::More: 0
version: 0.009
