--- #YAML:1.0
name:                Rose-DBx-Object-Indexed
version:             0.002
abstract:            full-text search for RDBO classes
license:             perl
author:              
    - Peter Karman <karman@cpan.org>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Class::C3:                     0
    Rose::DB::Object:              0
    Rose::DBx::Object::MoreHelpers: 0
    Scalar::Util:                  0
    SWISH::Prog:                   0.21
    Test::More:                    0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
